"""Residential EV customer-menu package."""

from .assembly import (
    AssembledMenu,
    MenuAssemblySettings,
    OfferSource,
    assemble_customer_menu,
    prune_ready_step_change_points,
)
from .degradation import (
    DEFAULT_LFP_PARAMETERS,
    DEFAULT_NMC_PARAMETERS,
    ChemistryDegradationParameters,
    DegradationAssessment,
    DegradationScoredMenu,
    DegradationSettings,
    assess_candidate_degradation,
    calendar_soc_stress,
    score_generated_menu,
)
from .exceptions import (
    EVMenuError,
    PhysicalConstraintError,
    SchemaValidationError,
    SignalValidationError,
)
from .feasibility import (
    RequestFeasibility,
    available_grid_energy_kwh,
    build_target_options,
    compute_buffer_energy,
    delivered_target_energy_kwh,
    evaluate_request_feasibility,
    minimum_required_departure_energy_kwh,
    minimum_required_target_soc,
    request_is_feasible,
    required_grid_energy_kwh,
)
from .menu import (
    CandidateKind,
    GeneratedMenu,
    MenuCandidate,
    MenuGenerationSettings,
    generate_candidate_menu,
)
from .optimization import (
    EndpointRole,
    FrontierSettings,
    OptimizedProfile,
    SavingFrontier,
    build_least_degradation_profile,
    build_sandwich_saving_frontier,
    build_saving_constrained_profile,
)
from .profiles import (
    ConstructedProfile,
    build_immediate_charging_profile,
    build_minimum_cost_charging_profile,
)
from .schemas import (
    ChargingProfile,
    ChargingSession,
    Chemistry,
    EVSpec,
    MenuOffer,
    MenuSettings,
    PlanningSignal,
    TargetOption,
    TargetSource,
)
from .validation import (
    ValidationCode,
    ValidationIssue,
    ValidationReport,
    ValidationTolerances,
    validate_charging_profile,
)

__all__ = [
    "DEFAULT_LFP_PARAMETERS",
    "DEFAULT_NMC_PARAMETERS",
    "AssembledMenu",
    "CandidateKind",
    "ChargingProfile",
    "ChargingSession",
    "Chemistry",
    "ChemistryDegradationParameters",
    "ConstructedProfile",
    "DegradationAssessment",
    "DegradationScoredMenu",
    "DegradationSettings",
    "EVMenuError",
    "EVSpec",
    "EndpointRole",
    "FrontierSettings",
    "GeneratedMenu",
    "MenuAssemblySettings",
    "MenuCandidate",
    "MenuGenerationSettings",
    "MenuOffer",
    "MenuSettings",
    "OfferSource",
    "OptimizedProfile",
    "PhysicalConstraintError",
    "PlanningSignal",
    "RequestFeasibility",
    "SavingFrontier",
    "SchemaValidationError",
    "SignalValidationError",
    "TargetOption",
    "TargetSource",
    "ValidationCode",
    "ValidationIssue",
    "ValidationReport",
    "ValidationTolerances",
    "assemble_customer_menu",
    "assess_candidate_degradation",
    "available_grid_energy_kwh",
    "build_immediate_charging_profile",
    "build_least_degradation_profile",
    "build_minimum_cost_charging_profile",
    "build_sandwich_saving_frontier",
    "build_saving_constrained_profile",
    "build_target_options",
    "calendar_soc_stress",
    "compute_buffer_energy",
    "delivered_target_energy_kwh",
    "evaluate_request_feasibility",
    "generate_candidate_menu",
    "minimum_required_departure_energy_kwh",
    "minimum_required_target_soc",
    "prune_ready_step_change_points",
    "request_is_feasible",
    "required_grid_energy_kwh",
    "score_generated_menu",
    "validate_charging_profile",
]
